using Dapper;

using JetComSmsSync.Modules.CDK.Models;

using Microsoft.Extensions.Configuration;

using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;

namespace JetComSmsSync.Modules.CDK
{
    public class DatabaseClient
    {
        private readonly string _autoRepairConnectionString;
        private readonly string _reportsConnectionString;

        public DatabaseClient(IConfiguration configuration)
        {
            _reportsConnectionString = configuration.GetConnectionString("V2Reports");
            _autoRepairConnectionString = configuration.GetConnectionString("AutoRepairSMS");
        }
        public AccountModel[] GetAccounts()
        {
            using var connection = new SqlConnection(_reportsConnectionString);
            var output = connection.Query<AccountModel>("SELECT * FROM [Accounts_CDK]").ToArray();
            return output;
        }

        public HelpEmployeeModel[] GetHelpEmployeeForCompare(string bigID)
        {
            using var connection = new SqlConnection(_autoRepairConnectionString);
            return connection.Query<HelpEmployeeModel>($"SELECT Id FROM CDK_HelpEmp WHERE BigID='{bigID}'").ToArray();
        }

        public int InsertHelpEmployees(IEnumerable<HelpEmployeeModel> items, string bigId)
        {
            using var connection = new SqlConnection(_autoRepairConnectionString);
            return connection.Execute($"INSERT INTO CDK_HelpEmp (BigID, Id, Name) VALUES ('{bigId}', @Id, @Name)", items);
        }

        public CustomerModel[] GetCustomersForCompare(string bigID)
        {
            using var connection = new SqlConnection(_autoRepairConnectionString);
            return connection.Query<CustomerModel>($"SELECT CustNo FROM CDK_Customer WHERE BigID='{bigID}'").ToArray();
        }

        public int InsertCustomers(IEnumerable<CustomerModel> items, string bigId)
        {
            using var connection = new SqlConnection(_autoRepairConnectionString);
            var query = @"INSERT INTO [dbo].[CDK_Customer]
           ([BigID]
           ,[Address]
           ,[AddressSecondLine]
           ,[Birthdate]
           ,[BlockEMail]
           ,[BlockMail]
           ,[BlockPhone]
           ,[BusinessPhone]
           ,[BusinessPhoneExt]
           ,[Cellular]
           ,[City]
           ,[Comment]
           ,[CommentDate]
           ,[ContactMethod]
           ,[Country]
           ,[County]
           ,[CreditLimit]
           ,[CurrentDue]
           ,[CustNo]
           ,[DateAdded]
           ,[DeleteDataDate]
           ,[DeleteDataTime]
           ,[DriverLicenseExpDate]
           ,[DriverLicenseStOrProv]
           ,[Email]
           ,[Email2]
           ,[Email3]
           ,[EmailDesc]
           ,[EmailDesc2]
           ,[EmailDesc3]
           ,[Employer]
           ,[ErrorLevel]
           ,[ErrorMessage]
           ,[FirstName]
           ,[Gender]
           ,[HomeFax]
           ,[HomePhone]
           ,[HostItemID]
           ,[InsAgency]
           ,[InsAgent]
           ,[InsAgentAddress1]
           ,[InsAgentAddress2]
           ,[InsAgentCity]
           ,[InsAgentPhone]
           ,[InsAgentState]
           ,[InsAgentZipOrPostalCode]
           ,[InsCompany]
           ,[InsCompanyAddress1]
           ,[InsCompanyAddress2]
           ,[InsCompanyCity]
           ,[InsCompanyPhone]
           ,[InsCompanyState]
           ,[InsCompanyZipOrPostalCode]
           ,[InsPolicyExpDate]
           ,[InsPolicyNo]
           ,[InsVerifiedBy]
           ,[InsVerifiedDate]
           ,[Language]
           ,[LastName]
           ,[LastUpdated]
           ,[Mailability]
           ,[MiddleName]
           ,[Name1]
           ,[Name2Company]
           ,[Name2First]
           ,[Name2Last]
           ,[Name2Middle]
           ,[Name2Suffix]
           ,[Name2Title]
           ,[NameBalances1]
           ,[NameCode]
           ,[NameCompany]
           ,[NameSuffix]
           ,[NameTitle]
           ,[OptOutDate]
           ,[OptOutTime]
           ,[Over120Due]
           ,[Over30Due]
           ,[Over60Due]
           ,[Over90Due]
           ,[Pager]
           ,[PartsCounterCode]
           ,[PartsFlag]
           ,[PartsType]
           ,[PreferredContactDay]
           ,[PreferredContactMethod]
           ,[PreferredContactTime]
           ,[PreferredLanguage]
           ,[SaleType]
           ,[SecondaryHomePhone]
           ,[ServiceCustomer]
           ,[SpecInstructions]
           ,[SpecInstructions2]
           ,[SpecInstructions3]
           ,[SpecInstructions4]
           ,[SpecInstructions5]
           ,[State]
           ,[TaxCode]
           ,[Telephone]
           ,[TextMessageCarrier]
           ,[TextMessagePhone]
           ,[Title1]
           ,[ZipOrPostalCode])
     VALUES
           (@BigID
           ,@Address
           ,@AddressSecondLine
           ,@Birthdate
           ,@BlockEMail
           ,@BlockMail
           ,@BlockPhone
           ,@BusinessPhone
           ,@BusinessPhoneExt
           ,@Cellular
           ,@City
           ,@Comment
           ,@CommentDate
           ,@ContactMethod
           ,@Country
           ,@County
           ,@CreditLimit
           ,@CurrentDue
           ,@CustNo
           ,@DateAdded
           ,@DeleteDataDate
           ,@DeleteDataTime
           ,@DriverLicenseExpDate
           ,@DriverLicenseStOrProv
           ,@Email
           ,@Email2
           ,@Email3
           ,@EmailDesc
           ,@EmailDesc2
           ,@EmailDesc3
           ,@Employer
           ,@ErrorLevel
           ,@ErrorMessage
           ,@FirstName
           ,@Gender
           ,@HomeFax
           ,@HomePhone
           ,@HostItemID
           ,@InsAgency
           ,@InsAgent
           ,@InsAgentAddress1
           ,@InsAgentAddress2
           ,@InsAgentCity
           ,@InsAgentPhone
           ,@InsAgentState
           ,@InsAgentZipOrPostalCode
           ,@InsCompany
           ,@InsCompanyAddress1
           ,@InsCompanyAddress2
           ,@InsCompanyCity
           ,@InsCompanyPhone
           ,@InsCompanyState
           ,@InsCompanyZipOrPostalCode
           ,@InsPolicyExpDate
           ,@InsPolicyNo
           ,@InsVerifiedBy
           ,@InsVerifiedDate
           ,@Language
           ,@LastName
           ,@LastUpdated
           ,@Mailability
           ,@MiddleName
           ,@Name1
           ,@Name2Company
           ,@Name2First
           ,@Name2Last
           ,@Name2Middle
           ,@Name2Suffix
           ,@Name2Title
           ,@NameBalances1
           ,@NameCode
           ,@NameCompany
           ,@NameSuffix
           ,@NameTitle
           ,@OptOutDate
           ,@OptOutTime
           ,@Over120Due
           ,@Over30Due
           ,@Over60Due
           ,@Over90Due
           ,@Pager
           ,@PartsCounterCode
           ,@PartsFlag
           ,@PartsType
           ,@PreferredContactDay
           ,@PreferredContactMethod
           ,@PreferredContactTime
           ,@PreferredLanguage
           ,@SaleType
           ,@SecondaryHomePhone
           ,@ServiceCustomer
           ,@SpecInstructions
           ,@SpecInstructions2
           ,@SpecInstructions3
           ,@SpecInstructions4
           ,@SpecInstructions5
           ,@State
           ,@TaxCode
           ,@Telephone
           ,@TextMessageCarrier
           ,@TextMessagePhone
           ,@Title1
           ,@ZipOrPostalCode)".Replace("@BigID", $"'{bigId}'");
            return connection.Execute(query, items);
        }

        public SRODModel[] GetSRODForCompare(string bigID)
        {
            using var connection = new SqlConnection(_autoRepairConnectionString);
            return connection.Query<SRODModel>($"SELECT RONumber FROM [dbo].[CDK_SROD] WHERE BigID='{bigID}'").ToArray();
        }

        public int InsertServiceRepairOrders(IEnumerable<SRODModel> items, string bigId)
        {
            var query = @"INSERT INTO [dbo].[CDK_SROD]
           ([BigID]
           ,[AddOnFlag]
           ,[Address]
           ,[ApptDate]
           ,[ApptFlag]
           ,[ApptTime]
           ,[BlockAutoMsg]
           ,[BookedDate]
           ,[BookedTime]
           ,[BookerNo]
           ,[Cashier]
           ,[CityStateZip]
           ,[ClosedDate]
           ,[ComebackFlag]
           ,[Comments]
           ,[ContactEmailAddress]
           ,[ContactPhoneNumber]
           ,[CustNo]
           ,[DeliveryDate]
           ,[EmailAddress]
           ,[EmailDesc]
           ,[EmailMultivalueCount]
           ,[ErrorLevel]
           ,[ErrorMessage]
           ,[EstComplDate]
           ,[EstComplTime]
           ,[HasCustPayFlag]
           ,[HasIntPayFlag]
           ,[HasWarrPayFlag]
           ,[HostItemID]
           ,[LastServiceDate]
           ,[LicenseNumber]
           ,[LotLocation]
           ,[Make]
           ,[MakeDesc]
           ,[Mileage]
           ,[MileageLastVisit]
           ,[MileageOut]
           ,[Model]
           ,[ModelDesc]
           ,[Name1]
           ,[Name2]
           ,[OpenDate]
           ,[OpenTime]
           ,[OrigPromisedDate]
           ,[OrigPromisedTime]
           ,[OrigWaiterFlag]
           ,[PhoneDesc]
           ,[PhoneExt]
           ,[PhoneMultivalueCount]
           ,[PhoneNumber]
           ,[PostedDate]
           ,[PriorityValue]
           ,[PromisedDate]
           ,[PromisedTime]
           ,[PurchaseOrderNo]
           ,[RONumber]
           ,[Remarks]
           ,[RentalFlag]
           ,[ServiceAdvisor]
           ,[SoldByDealerFlag]
           ,[SpecialCustFlag]
           ,[StatusCode]
           ,[StatusDesc]
           ,[TagNo]
           ,[VIN]
           ,[VehID]
           ,[VehicleColor]
           ,[VoidedDate]
           ,[WaiterFlag]
           ,[Year]
           ,[Zip]
           ,[dedActualAmount]
           ,[dedLaborAmount]
           ,[dedLaborType]
           ,[dedLineCodes]
           ,[dedMaximumAmount]
           ,[dedMultivalueCount]
           ,[dedPartsAmount]
           ,[dedSequenceNo]
           ,[disAppliedBy]
           ,[disClassOrType]
           ,[disDebitAccountNo]
           ,[disDebitControlNo]
           ,[disDebitTargetCo]
           ,[disDesc]
           ,[disDiscountID]
           ,[disLaborDiscount]
           ,[disLevel]
           ,[disLineCode]
           ,[disLopSeqNo]
           ,[disManagerOverride]
           ,[disMultivalueCount]
           ,[disOriginalDiscount]
           ,[disOverrideAmount]
           ,[disOverrideGPAmount]
           ,[disOverrideGPPercent]
           ,[disOverridePercent]
           ,[disOverrideTarget]
           ,[disPartsDiscount]
           ,[disSequenceNo]
           ,[disTotalDiscount]
           ,[disUserID]
           ,[feeCost]
           ,[feeFeeID]
           ,[feeLOPorPartFlag]
           ,[feeLOPorPartSeqNo]
           ,[feeLaborType]
           ,[feeLineCode]
           ,[feeMcdPercentage]
           ,[feeMultivalueCount]
           ,[feeOpCode]
           ,[feeOpCodeDesc]
           ,[feeSale]
           ,[feeSequenceNo]
           ,[feeType]
           ,[hrsActualHours]
           ,[hrsCost]
           ,[hrsFlagHours]
           ,[hrsHourType]
           ,[hrsLaborType]
           ,[hrsLineCode]
           ,[hrsMcdPercentage]
           ,[hrsMultivalueCount]
           ,[hrsOtherHours]
           ,[hrsPercentage]
           ,[hrsSale]
           ,[hrsSequenceNo]
           ,[hrsSoldHours]
           ,[hrsTechNo]
           ,[hrsTimeCardHours]
           ,[lbrActualHours]
           ,[lbrComebackFlag]
           ,[lbrComebackRO]
           ,[lbrComebackSA]
           ,[lbrComebackTech]
           ,[lbrCost]
           ,[lbrFlagHours]
           ,[lbrForcedShopCharge]
           ,[lbrLaborType]
           ,[lbrLineCode]
           ,[lbrMcdPercentage]
           ,[lbrMultivalueCount]
           ,[lbrOpCode]
           ,[lbrOpCodeDesc]
           ,[lbrOperationType]
           ,[lbrOtherHours]
           ,[lbrSale]
           ,[lbrSequenceNo]
           ,[lbrSoldHours]
           ,[lbrTechNo]
           ,[lbrTimeCardHours]
           ,[linActualWork]
           ,[linAddOnFlag]
           ,[linBookerNo]
           ,[linCampaignCode]
           ,[linCause]
           ,[linComebackFlag]
           ,[linComplaintCode]
           ,[linDispatchCode]
           ,[linEstDuration]
           ,[linLineCode]
           ,[linMultivalueCount]
           ,[linServiceRequest]
           ,[linStatusCode]
           ,[linStatusDesc]
           ,[linStoryEmployeeNo]
           ,[linStorySequenceNo]
           ,[linStoryText]
           ,[mlsCost]
           ,[mlsLaborType]
           ,[mlsLineCode]
           ,[mlsMcdPercentage]
           ,[mlsMultivalueCount]
           ,[mlsOpCode]
           ,[mlsOpCodeDesc]
           ,[mlsSale]
           ,[mlsSequenceNo]
           ,[mlsType]
           ,[payCPTotal]
           ,[payInsuranceFlag]
           ,[payMultivalueCount]
           ,[payPaymentAmount]
           ,[payPaymentCode]
           ,[payPaymentsMade]
           ,[prtBin1]
           ,[prtClass]
           ,[prtComp]
           ,[prtCompLineCode]
           ,[prtCoreCost]
           ,[prtCoreSale]
           ,[prtCost]
           ,[prtDesc]
           ,[prtEmployeeNo]
           ,[prtExtendedCost]
           ,[prtExtendedSale]
           ,[prtLaborSequenceNo]
           ,[prtLaborType]
           ,[prtLineCode]
           ,[prtList]
           ,[prtMcdPercentage]
           ,[prtMultivalueCount]
           ,[prtOutsideSalesmanNo]
           ,[prtPartNo]
           ,[prtQtyBackordered]
           ,[prtQtyFilled]
           ,[prtQtyOnHand]
           ,[prtQtyOrdered]
           ,[prtQtySold]
           ,[prtSale]
           ,[prtSequenceNo]
           ,[prtSource]
           ,[prtSpecialStatus]
           ,[prtUnitServiceCharge]
           ,[punAlteredFlag]
           ,[punDuration]
           ,[punLineCode]
           ,[punMultivalueCount]
           ,[punTechNo]
           ,[punTimeOff]
           ,[punTimeOn]
           ,[punWorkDate]
           ,[punWorkType]
           ,[rapApptID]
           ,[rapMultivalueCount]
           ,[totActualHours]
           ,[totCoreCost]
           ,[totCoreSale]
           ,[totDiscount]
           ,[totFlagHours]
           ,[totForcedShopCharge]
           ,[totLaborCost]
           ,[totLaborCount]
           ,[totLaborDiscount]
           ,[totLaborSale]
           ,[totLaborSalePostDed]
           ,[totLocalTax]
           ,[totLubeCost]
           ,[totLubeCount]
           ,[totLubeSale]
           ,[totMiscCost]
           ,[totMiscCount]
           ,[totMiscSale]
           ,[totMultivalueCount]
           ,[totOtherHours]
           ,[totPartsCost]
           ,[totPartsCount]
           ,[totPartsDiscount]
           ,[totPartsSale]
           ,[totPartsSalePostDed]
           ,[totPayType]
           ,[totRoCost]
           ,[totRoSale]
           ,[totRoSalePostDed]
           ,[totRoTax]
           ,[totShopChargeCost]
           ,[totShopChargeSale]
           ,[totSoldHours]
           ,[totStateTax]
           ,[totSubletCost]
           ,[totSubletCount]
           ,[totSubletSale]
           ,[totSupp2Tax]
           ,[totSupp3Tax]
           ,[totSupp4Tax]
           ,[totTimeCardHours]
           ,[warAuthorizationCode]
           ,[warClaimType]
           ,[warConditionCode]
           ,[warFailedPartNo]
           ,[warFailedPartsCount]
           ,[warFailureCode]
           ,[warLaborSequenceNo]
           ,[warLineCode]
           ,[warMultivalueCount])
     VALUES
           (@BigID
           ,@AddOnFlag
           ,@Address
           ,@ApptDate
           ,@ApptFlag
           ,@ApptTime
           ,@BlockAutoMsg
           ,@BookedDate
           ,@BookedTime
           ,@BookerNo
           ,@Cashier
           ,@CityStateZip
           ,@ClosedDate
           ,@ComebackFlag
           ,@Comments
           ,@ContactEmailAddress
           ,@ContactPhoneNumber
           ,@CustNo
           ,@DeliveryDate
           ,@EmailAddress
           ,@EmailDesc
           ,@EmailMultivalueCount
           ,@ErrorLevel
           ,@ErrorMessage
           ,@EstComplDate
           ,@EstComplTime
           ,@HasCustPayFlag
           ,@HasIntPayFlag
           ,@HasWarrPayFlag
           ,@HostItemID
           ,@LastServiceDate
           ,@LicenseNumber
           ,@LotLocation
           ,@Make
           ,@MakeDesc
           ,@Mileage
           ,@MileageLastVisit
           ,@MileageOut
           ,@Model
           ,@ModelDesc
           ,@Name1
           ,@Name2
           ,@OpenDate
           ,@OpenTime
           ,@OrigPromisedDate
           ,@OrigPromisedTime
           ,@OrigWaiterFlag
           ,@PhoneDesc
           ,@PhoneExt
           ,@PhoneMultivalueCount
           ,@PhoneNumber
           ,@PostedDate
           ,@PriorityValue
           ,@PromisedDate
           ,@PromisedTime
           ,@PurchaseOrderNo
           ,@RONumber
           ,@Remarks
           ,@RentalFlag
           ,@ServiceAdvisor
           ,@SoldByDealerFlag
           ,@SpecialCustFlag
           ,@StatusCode
           ,@StatusDesc
           ,@TagNo
           ,@VIN
           ,@VehID
           ,@VehicleColor
           ,@VoidedDate
           ,@WaiterFlag
           ,@Year
           ,@Zip
           ,@dedActualAmount
           ,@dedLaborAmount
           ,@dedLaborType
           ,@dedLineCodes
           ,@dedMaximumAmount
           ,@dedMultivalueCount
           ,@dedPartsAmount
           ,@dedSequenceNo
           ,@disAppliedBy
           ,@disClassOrType
           ,@disDebitAccountNo
           ,@disDebitControlNo
           ,@disDebitTargetCo
           ,@disDesc
           ,@disDiscountID
           ,@disLaborDiscount
           ,@disLevel
           ,@disLineCode
           ,@disLopSeqNo
           ,@disManagerOverride
           ,@disMultivalueCount
           ,@disOriginalDiscount
           ,@disOverrideAmount
           ,@disOverrideGPAmount
           ,@disOverrideGPPercent
           ,@disOverridePercent
           ,@disOverrideTarget
           ,@disPartsDiscount
           ,@disSequenceNo
           ,@disTotalDiscount
           ,@disUserID
           ,@feeCost
           ,@feeFeeID
           ,@feeLOPorPartFlag
           ,@feeLOPorPartSeqNo
           ,@feeLaborType
           ,@feeLineCode
           ,@feeMcdPercentage
           ,@feeMultivalueCount
           ,@feeOpCode
           ,@feeOpCodeDesc
           ,@feeSale
           ,@feeSequenceNo
           ,@feeType
           ,@hrsActualHours
           ,@hrsCost
           ,@hrsFlagHours
           ,@hrsHourType
           ,@hrsLaborType
           ,@hrsLineCode
           ,@hrsMcdPercentage
           ,@hrsMultivalueCount
           ,@hrsOtherHours
           ,@hrsPercentage
           ,@hrsSale
           ,@hrsSequenceNo
           ,@hrsSoldHours
           ,@hrsTechNo
           ,@hrsTimeCardHours
           ,@lbrActualHours
           ,@lbrComebackFlag
           ,@lbrComebackRO
           ,@lbrComebackSA
           ,@lbrComebackTech
           ,@lbrCost
           ,@lbrFlagHours
           ,@lbrForcedShopCharge
           ,@lbrLaborType
           ,@lbrLineCode
           ,@lbrMcdPercentage
           ,@lbrMultivalueCount
           ,@lbrOpCode
           ,@lbrOpCodeDesc
           ,@lbrOperationType
           ,@lbrOtherHours
           ,@lbrSale
           ,@lbrSequenceNo
           ,@lbrSoldHours
           ,@lbrTechNo
           ,@lbrTimeCardHours
           ,@linActualWork
           ,@linAddOnFlag
           ,@linBookerNo
           ,@linCampaignCode
           ,@linCause
           ,@linComebackFlag
           ,@linComplaintCode
           ,@linDispatchCode
           ,@linEstDuration
           ,@linLineCode
           ,@linMultivalueCount
           ,@linServiceRequest
           ,@linStatusCode
           ,@linStatusDesc
           ,@linStoryEmployeeNo
           ,@linStorySequenceNo
           ,@linStoryText
           ,@mlsCost
           ,@mlsLaborType
           ,@mlsLineCode
           ,@mlsMcdPercentage
           ,@mlsMultivalueCount
           ,@mlsOpCode
           ,@mlsOpCodeDesc
           ,@mlsSale
           ,@mlsSequenceNo
           ,@mlsType
           ,@payCPTotal
           ,@payInsuranceFlag
           ,@payMultivalueCount
           ,@payPaymentAmount
           ,@payPaymentCode
           ,@payPaymentsMade
           ,@prtBin1
           ,@prtClass
           ,@prtComp
           ,@prtCompLineCode
           ,@prtCoreCost
           ,@prtCoreSale
           ,@prtCost
           ,@prtDesc
           ,@prtEmployeeNo
           ,@prtExtendedCost
           ,@prtExtendedSale
           ,@prtLaborSequenceNo
           ,@prtLaborType
           ,@prtLineCode
           ,@prtList
           ,@prtMcdPercentage
           ,@prtMultivalueCount
           ,@prtOutsideSalesmanNo
           ,@prtPartNo
           ,@prtQtyBackordered
           ,@prtQtyFilled
           ,@prtQtyOnHand
           ,@prtQtyOrdered
           ,@prtQtySold
           ,@prtSale
           ,@prtSequenceNo
           ,@prtSource
           ,@prtSpecialStatus
           ,@prtUnitServiceCharge
           ,@punAlteredFlag
           ,@punDuration
           ,@punLineCode
           ,@punMultivalueCount
           ,@punTechNo
           ,@punTimeOff
           ,@punTimeOn
           ,@punWorkDate
           ,@punWorkType
           ,@rapApptID
           ,@rapMultivalueCount
           ,@totActualHours
           ,@totCoreCost
           ,@totCoreSale
           ,@totDiscount
           ,@totFlagHours
           ,@totForcedShopCharge
           ,@totLaborCost
           ,@totLaborCount
           ,@totLaborDiscount
           ,@totLaborSale
           ,@totLaborSalePostDed
           ,@totLocalTax
           ,@totLubeCost
           ,@totLubeCount
           ,@totLubeSale
           ,@totMiscCost
           ,@totMiscCount
           ,@totMiscSale
           ,@totMultivalueCount
           ,@totOtherHours
           ,@totPartsCost
           ,@totPartsCount
           ,@totPartsDiscount
           ,@totPartsSale
           ,@totPartsSalePostDed
           ,@totPayType
           ,@totRoCost
           ,@totRoSale
           ,@totRoSalePostDed
           ,@totRoTax
           ,@totShopChargeCost
           ,@totShopChargeSale
           ,@totSoldHours
           ,@totStateTax
           ,@totSubletCost
           ,@totSubletCount
           ,@totSubletSale
           ,@totSupp2Tax
           ,@totSupp3Tax
           ,@totSupp4Tax
           ,@totTimeCardHours
           ,@warAuthorizationCode
           ,@warClaimType
           ,@warConditionCode
           ,@warFailedPartNo
           ,@warFailedPartsCount
           ,@warFailureCode
           ,@warLaborSequenceNo
           ,@warLineCode
           ,@warMultivalueCount)".Replace("@BigID", $"'{bigId}'");
            using var connection = new SqlConnection(_autoRepairConnectionString);
            var output = connection.Execute(query, items);
            return output;
        }
    }
}
