namespace JetComSmsSync.Modules.CDK.Models
{
    public class CustomerModel
    {
        public string Address { get; set; }
        public string AddressSecondLine { get; set; }
        public string BirthDate { get; set; }
        public string BlockEMail { get; set; }
        public string BlockMail { get; set; }
        public string BlockPhone { get; set; }
        public string BusinessPhone { get; set; }
        public string BusinessPhoneExt { get; set; }
        public string Cellular { get; set; }
        public string City { get; set; }
        public string Comment { get; set; }
        public string CommentDate { get; set; }
        public string ContactMethod { get; set; }
        public string Country { get; set; }
        public string County { get; set; }
        public string CreditLimit { get; set; }
        public string CurrentDue { get; set; }
        public string CustNo { get; set; }
        public string DateAdded { get; set; }
        public string DeleteDataDate { get; set; }
        public string DeleteDataTime { get; set; }
        public string DriverLicenseExpDate { get; set; }
        public string DriverLicenseStOrProv { get; set; }
        public string Email { get; set; }
        public string Email2 { get; set; }
        public string Email3 { get; set; }
        public string EmailDesc { get; set; }
        public string EmailDesc2 { get; set; }
        public string EmailDesc3 { get; set; }
        public string Employer { get; set; }
        public string ErrorLevel { get; set; }
        public string ErrorMessage { get; set; }
        public string FirstName { get; set; }
        public string Gender { get; set; }
        public string HomeFax { get; set; }
        public string HomePhone { get; set; }
        public string HostItemID { get; set; }
        public string InsAgency { get; set; }
        public string InsAgent { get; set; }
        public string InsAgentAddress1 { get; set; }
        public string InsAgentAddress2 { get; set; }
        public string InsAgentCity { get; set; }
        public string InsAgentPhone { get; set; }
        public string InsAgentState { get; set; }
        public string InsAgentZipOrPostalCode { get; set; }
        public string InsCompany { get; set; }
        public string InsCompanyAddress1 { get; set; }
        public string InsCompanyAddress2 { get; set; }
        public string InsCompanyCity { get; set; }
        public string InsCompanyPhone { get; set; }
        public string InsCompanyState { get; set; }
        public string InsCompanyZipOrPostalCode { get; set; }
        public string InsPolicyExpDate { get; set; }
        public string InsPolicyNo { get; set; }
        public string InsVerifiedBy { get; set; }
        public string InsVerifiedDate { get; set; }
        public string Language { get; set; }
        public string LastName { get; set; }
        public string LastUpdated { get; set; }
        public string Mailability { get; set; }
        public string MiddleName { get; set; }
        public string Name1 { get; set; }
        public string Name2Company { get; set; }
        public string Name2First { get; set; }
        public string Name2Last { get; set; }
        public string Name2Middle { get; set; }
        public string Name2Suffix { get; set; }
        public string Name2Title { get; set; }
        public string NameBalances1 { get; set; }
        public string NameCode { get; set; }
        public string NameCompany { get; set; }
        public string NameSuffix { get; set; }
        public string NameTitle { get; set; }
        public string OptOutDate { get; set; }
        public string OptOutTime { get; set; }
        public string Over120Due { get; set; }
        public string Over30Due { get; set; }
        public string Over60Due { get; set; }
        public string Over90Due { get; set; }
        public string Pager { get; set; }
        public string PartsCounterCode { get; set; }
        public string PartsFlag { get; set; }
        public string PartsType { get; set; }
        public string PreferredContactDay { get; set; }
        public string PreferredContactMethod { get; set; }
        public string PreferredContactTime { get; set; }
        public string PreferredLanguage { get; set; }
        public string SaleType { get; set; }
        public string SecondaryHomePhone { get; set; }
        public string ServiceCustomer { get; set; }
        public string SpecInstructions { get; set; }
        public string SpecInstructions2 { get; set; }
        public string SpecInstructions3 { get; set; }
        public string SpecInstructions4 { get; set; }
        public string SpecInstructions5 { get; set; }
        public string State { get; set; }
        public string TaxCode { get; set; }
        public string Telephone { get; set; }
        public string TextMessageCarrier { get; set; }
        public string TextMessagePhone { get; set; }
        public string Title1 { get; set; }
        public string ZipOrPostalCode { get; set; }
    }
}
