namespace JetComSmsSync.Modules.CDK.Models
{
    public class SRODModel
    {
        public string AddOnFlag { get; set; }
        public string Address { get; set; }
        public string ApptDate { get; set; }
        public string ApptFlag { get; set; }
        public string ApptTime { get; set; }
        public string BlockAutoMsg { get; set; }
        public string BookedDate { get; set; }
        public string BookedTime { get; set; }
        public string BookerNo { get; set; }
        public string Cashier { get; set; }
        public string CityStateZip { get; set; }
        public string ClosedDate { get; set; }
        public string ComebackFlag { get; set; }
        public string Comments { get; set; }
        public string ContactEmailAddress { get; set; }
        public string ContactPhoneNumber { get; set; }
        public string CustNo { get; set; }
        public string DeliveryDate { get; set; }
        public string EmailAddress { get; set; }
        public string EmailDesc { get; set; }
        public string EmailMultivalueCount { get; set; }
        public string ErrorLevel { get; set; }
        public string ErrorMessage { get; set; }
        public string EstComplDate { get; set; }
        public string EstComplTime { get; set; }
        public string HasCustPayFlag { get; set; }
        public string HasIntPayFlag { get; set; }
        public string HostItemID { get; set; }
        public string LastServiceDate { get; set; }
        public string LicenseNumber { get; set; }
        public string LotLocation { get; set; }
        public string Make { get; set; }
        public string MakeDesc { get; set; }
        public string Mileage { get; set; }
        public string MileageLastVisit { get; set; }
        public string MileageOut { get; set; }
        public string Model { get; set; }
        public string ModelDesc { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string OpenDate { get; set; }
        public string OpenTime { get; set; }
        public string OrigPromisedDate { get; set; }
        public string OrigPromisedTime { get; set; }
        public string OrigWaiterFlag { get; set; }
        public string PhoneDesc { get; set; }
        public string PhoneExt { get; set; }
        public string PhoneMultivalueCount { get; set; }
        public string PhoneNumber { get; set; }
        public string PostedDate { get; set; }
        public string PriorityValue { get; set; }
        public string PromisedDate { get; set; }
        public string PromisedTime { get; set; }
        public string PurchaseOrderNo { get; set; }
        public string RONumber { get; set; }
        public string Remarks { get; set; }
        public string RentalFlag { get; set; }
        public string ServiceAdvisor { get; set; }
        public string SoldByDealerFlag { get; set; }
        public string SpecialCustFlag { get; set; }
        public string StatusCode { get; set; }
        public string StatusDesc { get; set; }
        public string TagNo { get; set; }
        public string VIN { get; set; }
        public string VehID { get; set; }
        public string VehicleColor { get; set; }
        public string VoidedDate { get; set; }
        public string WaiterFlag { get; set; }
        public string Year { get; set; }
        public string Zip { get; set; }
        public string dedActualAmount { get; set; }
        public string dedLaborAmount { get; set; }
        public string dedLineCodes { get; set; }
        public string dedMaximumAmount { get; set; }
        public string dedMultivalueCount { get; set; }
        public string dedPartsAmount { get; set; }
        public string dedSequenceNo { get; set; }
        public string disAppliedBy { get; set; }
        public string disClassOrType { get; set; }
        public string disDebitAccountNo { get; set; }
        public string disDebitControlNo { get; set; }
        public string disDebitTargetCo { get; set; }
        public string disDiscountID { get; set; }
        public string disLaborDiscount { get; set; }
        public string disLevel { get; set; }
        public string disLineCode { get; set; }
        public string disLopSeqNo { get; set; }
        public string disManagerOverride { get; set; }
        public string disMultivalueCount { get; set; }
        public string disOriginalDiscount { get; set; }
        public string disOverrideAmount { get; set; }
        public string disOverrideGPAmount { get; set; }
        public string disOverrideGPPercent { get; set; }
        public string disOverridePercent { get; set; }
        public string disOverrideTarget { get; set; }
        public string disPartsDiscount { get; set; }
        public string disSequenceNo { get; set; }
        public string disTotalDiscount { get; set; }
        public string disUserID { get; set; }
        public string feeCost { get; set; }
        public string feeFeeID { get; set; }
        public string feeLOPorPartFlag { get; set; }
        public string feeLOPorPartSeqNo { get; set; }
        public string feeLaborType { get; set; }
        public string feeLineCode { get; set; }
        public string feeMcdPercentage { get; set; }
        public string feeMultivalueCount { get; set; }
        public string feeOpCode { get; set; }
        public string feeOpCodeDesc { get; set; }
        public string feeSale { get; set; }
        public string feeSequenceNo { get; set; }
        public string feeType { get; set; }
        public string HasWarrPayFlag { get; set; }
        public string hrsActualHours { get; set; }
        public string hrsCost { get; set; }
        public string hrsFlagHours { get; set; }
        public string hrsHourType { get; set; }
        public string hrsLaborType { get; set; }
        public string hrsLineCode { get; set; }
        public string hrsMcdPercentage { get; set; }
        public string hrsMultivalueCount { get; set; }
        public string hrsOtherHours { get; set; }
        public string hrsPercentage { get; set; }
        public string hrsSale { get; set; }
        public string hrsSequenceNo { get; set; }
        public string hrsSoldHours { get; set; }
        public string hrsTechNo { get; set; }
        public string hrsTimeCardHours { get; set; }
        public string lbrActualHours { get; set; }
        public string lbrComebackFlag { get; set; }
        public string lbrComebackRO { get; set; }
        public string lbrComebackSA { get; set; }
        public string lbrComebackTech { get; set; }
        public string lbrCost { get; set; }
        public string lbrFlagHours { get; set; }
        public string lbrForcedShopCharge { get; set; }
        public string lbrLaborType { get; set; }
        public string lbrLineCode { get; set; }
        public string lbrMcdPercentage { get; set; }
        public string lbrMultivalueCount { get; set; }
        public string lbrOpCode { get; set; }
        public string lbrOpCodeDesc { get; set; }
        public string lbrOperationType { get; set; }
        public string lbrOtherHours { get; set; }
        public string lbrSale { get; set; }
        public string lbrSequenceNo { get; set; }
        public string lbrSoldHours { get; set; }
        public string lbrTechNo { get; set; }
        public string lbrTimeCardHours { get; set; }
        public string linActualWork { get; set; }
        public string linAddOnFlag { get; set; }
        public string linBookerNo { get; set; }
        public string linCampaignCode { get; set; }
        public string linCause { get; set; }
        public string linComebackFlag { get; set; }
        public string linComplaintCode { get; set; }
        public string linDispatchCode { get; set; }
        public string linEstDuration { get; set; }
        public string linLineCode { get; set; }
        public string linMultivalueCount { get; set; }
        public string linServiceRequest { get; set; }
        public string linStatusCode { get; set; }
        public string linStatusDesc { get; set; }
        public string linStoryEmployeeNo { get; set; }
        public string linStorySequenceNo { get; set; }
        public string linStoryText { get; set; }
        public string mlsCost { get; set; }
        public string mlsLaborType { get; set; }
        public string mlsLineCode { get; set; }
        public string mlsMcdPercentage { get; set; }
        public string mlsMultivalueCount { get; set; }
        public string mlsOpCode { get; set; }
        public string mlsOpCodeDesc { get; set; }
        public string mlsSale { get; set; }
        public string mlsSequenceNo { get; set; }
        public string mlsType { get; set; }
        public string payCPTotal { get; set; }
        public string payInsuranceFlag { get; set; }
        public string payMultivalueCount { get; set; }
        public string payPaymentAmount { get; set; }
        public string payPaymentCode { get; set; }
        public string payPaymentsMade { get; set; }
        public string prtBin1 { get; set; }
        public string prtClass { get; set; }
        public string prtComp { get; set; }
        public string prtCompLineCode { get; set; }
        public string prtCoreCost { get; set; }
        public string prtCoreSale { get; set; }
        public string prtCost { get; set; }
        public string prtDesc { get; set; }
        public string prtEmployeeNo { get; set; }
        public string prtExtendedCost { get; set; }
        public string prtExtendedSale { get; set; }
        public string prtLaborSequenceNo { get; set; }
        public string prtLaborType { get; set; }
        public string prtLineCode { get; set; }
        public string prtList { get; set; }
        public string prtMcdPercentage { get; set; }
        public string prtMultivalueCount { get; set; }
        public string prtOutsideSalesmanNo { get; set; }
        public string prtPartNo { get; set; }
        public string prtQtyBackordered { get; set; }
        public string prtQtyFilled { get; set; }
        public string prtQtyOnHand { get; set; }
        public string prtQtyOrdered { get; set; }
        public string prtQtySold { get; set; }
        public string prtSale { get; set; }
        public string prtSequenceNo { get; set; }
        public string prtSource { get; set; }
        public string prtSpecialStatus { get; set; }
        public string prtUnitServiceCharge { get; set; }
        public string punAlteredFlag { get; set; }
        public string punDuration { get; set; }
        public string punLineCode { get; set; }
        public string punMultivalueCount { get; set; }
        public string punTechNo { get; set; }
        public string punTimeOff { get; set; }
        public string punTimeOn { get; set; }
        public string punWorkDate { get; set; }
        public string punWorkType { get; set; }
        public string rapApptID { get; set; }
        public string rapMultivalueCount { get; set; }
        public string totActualHours { get; set; }
        public string totCoreCost { get; set; }
        public string totCoreSale { get; set; }
        public string totDiscount { get; set; }
        public string totFlagHours { get; set; }
        public string totForcedShopCharge { get; set; }
        public string totLaborCost { get; set; }
        public string totLaborCount { get; set; }
        public string totLaborDiscount { get; set; }
        public string totLaborSale{ get; set; }
        public string totLaborSalePostDed { get; set; }
        public string totLocalTax { get; set; }
        public string totLubeCost { get; set; }
        public string totLubeCount { get; set; }
        public string totLubeSale { get; set; }
        public string totMiscCost { get; set; }
        public string totMiscCount { get; set; }
        public string totMiscSale { get; set; }
        public string totMultivalueCount { get; set; }
        public string totOtherHours { get; set; }
        public string totPartsCost { get; set; }
        public string totPartsCount { get; set; }
        public string totPartsDiscount { get; set; }
        public string totPartsSale { get; set; }
        public string totPartsSalePostDed { get; set; }
        public string totPayType { get; set; }
        public string totRoCost { get; set; }
        public string totRoSale { get; set; }
        public string totRoSalePostDed { get; set; }
        public string totRoTax { get; set; }
        public string totShopChargeCost { get; set; }
        public string totShopChargeSale { get; set; }
        public string totSoldHours { get; set; }
        public string totStateTax { get; set; }
        public string totSubletCost { get; set; }
        public string totSubletCount { get; set; }
        public string totSubletSale { get; set; }
        public string totSupp2Tax { get; set; }
        public string totSupp3Tax { get; set; }
        public string totSupp4Tax { get; set; }
        public string totTimeCardHours { get; set; }
        public string warAuthorizationCode { get; set; }
        public string warClaimType { get; set; }
        public string warConditionCode { get; set; }
        public string warFailedPartNo { get; set; }
        public string warFailedPartsCount { get; set; }
        public string warFailureCode { get; set; }
        public string warLaborSequenceNo { get; set; }
        public string warLineCode { get; set; }
        public string warMultivalueCount { get; set; }

        public string dedLaborType { get; set; }
        public string disDesc { get; set; }

    }
}
